package UserInterface.Plantillas;

import UserInterface.RegistroAntecedente;
import javax.swing.JOptionPane;

/**
 *
 * @author epale
 */
public class PlantillaAntecedente extends javax.swing.JPanel {
    public enum TipoAntecedente {
        Enfermedad,
        Alergia,
        Vacuna,
        Cirugia,
        Medicamento
    }
    
    private TipoAntecedente tipoAntecedente;
    private int idAntecedente;
    private int idPaciente = 20;
    RegistroAntecedente panelPadre;
    
    public PlantillaAntecedente(RegistroAntecedente panelPadre, TipoAntecedente tipoAntecedente, int idAntecedente, String nombreAntecedente, String fecha) {
        initComponents();
        this.panelPadre = panelPadre;
        this.tipoAntecedente = tipoAntecedente;
        this.idAntecedente = idAntecedente;
        this.LabelNombre.setText(nombreAntecedente);
        if (fecha != null) {
            this.LabelFecha.setText(fecha);
        }
    }

    private void eliminarAntecedenteEnfermedad() {
        DAO.EnfermedadDAO enfermedadDAO = new DAO.EnfermedadDAO();
        int resultado;
        
        try {
            resultado = enfermedadDAO.eliminarEnfermedadDeAntecedente(this.idPaciente, this.idAntecedente);
        } catch (java.sql.SQLException error) {
            //TODO: loggear excepcion
            JOptionPane.showMessageDialog(null, "Ocurrió un error, vuelva a intentarlo más tarde", "Error de conexión", JOptionPane.ERROR_MESSAGE);
            resultado = -1;
        }
        
        if (resultado == 1) {
            JOptionPane.showMessageDialog(null, "La enfermedad fue borrada de su antecedente exitosamente", "Operación exitosa", JOptionPane.OK_OPTION);
        }
        else if (resultado == 0) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error al intentar eliminar la enfermedad", "Operación fallida", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void eliminarAntecedenteAlergia() {
        
    }
    
    private void eliminarAntecedenteVacuna() {
        
    }
    
    private void eliminarAntecedenteCirugia() {
        
    }
    
    private void eliminarAntecedenteMedicamento() {
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        LabelFecha = new javax.swing.JLabel();
        LabelFechaRegistro = new javax.swing.JLabel();
        LabelNombre = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7));
        setMaximumSize(new java.awt.Dimension(1280, 85));
        setMinimumSize(new java.awt.Dimension(300, 50));
        setPreferredSize(new java.awt.Dimension(650, 85));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(181, 220, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(181, 220, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        LabelFecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelFecha.setText("No disponible");
        LabelFecha.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 5, 0));
        jPanel1.add(LabelFecha, java.awt.BorderLayout.PAGE_END);

        LabelFechaRegistro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelFechaRegistro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelFechaRegistro.setText("Fecha de registro: ");
        LabelFechaRegistro.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 0, 0));
        jPanel1.add(LabelFechaRegistro, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        LabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNombre.setText("nombre");
        LabelNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        LabelNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(LabelNombre, java.awt.BorderLayout.PAGE_START);

        jButton1.setText("Quitar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, java.awt.BorderLayout.LINE_END);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        switch (this.tipoAntecedente) {
            case Enfermedad -> {
                eliminarAntecedenteEnfermedad();
                this.panelPadre.recuperarAntecedenteEnfermedades();
            }
            case Alergia -> eliminarAntecedenteAlergia();
            case Vacuna -> eliminarAntecedenteVacuna();
            case Cirugia -> eliminarAntecedenteCirugia();
            case Medicamento -> eliminarAntecedenteMedicamento();
            default -> {break;}
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFecha;
    private javax.swing.JLabel LabelFechaRegistro;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
