package UserInterface;

/**
 *
 * @author epale
 */
public class RegistroAntecedente extends javax.swing.JFrame {

    public RegistroAntecedente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelEnfermedades = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ComboBoxEnfermedades = new javax.swing.JComboBox<>();
        BotonAgregarEnfermedad = new javax.swing.JButton();
        PanelAntecedenteEnfermedades = new javax.swing.JPanel();
        PanelAlergias = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ComboBoxAlergias = new javax.swing.JComboBox<>();
        BotonAgregarAlergia = new javax.swing.JButton();
        PanelAntecedenteAlergias = new javax.swing.JPanel();
        PanelVacunas = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ComboBoxVacunas = new javax.swing.JComboBox<>();
        BotonAgregarVacuna = new javax.swing.JButton();
        PanelAntecedenteVacunas = new javax.swing.JPanel();
        PanelCirugias = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ComboBoxCirugias = new javax.swing.JComboBox<>();
        BotonAgregarCirugia = new javax.swing.JButton();
        PanelAntecedenteCirugias = new javax.swing.JPanel();
        PanelMedicamentos = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ComboBoxMedicamentos = new javax.swing.JComboBox<>();
        BotonAgregarMedicamento = new javax.swing.JButton();
        PanelAntecedenteMedicamentos = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        PanelEnfermedades.setLayout(new java.awt.BorderLayout());

        jPanel10.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Selecciona una enfermedad");

        ComboBoxEnfermedades.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboBoxEnfermedades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecciona una opción>" }));
        ComboBoxEnfermedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxEnfermedadesActionPerformed(evt);
            }
        });

        BotonAgregarEnfermedad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonAgregarEnfermedad.setText("Agregar al antecedente");
        BotonAgregarEnfermedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarEnfermedadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(ComboBoxEnfermedades, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(BotonAgregarEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(613, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxEnfermedades, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAgregarEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        PanelEnfermedades.add(jPanel10, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout PanelAntecedenteEnfermedadesLayout = new javax.swing.GroupLayout(PanelAntecedenteEnfermedades);
        PanelAntecedenteEnfermedades.setLayout(PanelAntecedenteEnfermedadesLayout);
        PanelAntecedenteEnfermedadesLayout.setHorizontalGroup(
            PanelAntecedenteEnfermedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1265, Short.MAX_VALUE)
        );
        PanelAntecedenteEnfermedadesLayout.setVerticalGroup(
            PanelAntecedenteEnfermedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        PanelEnfermedades.add(PanelAntecedenteEnfermedades, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Enfermedades", PanelEnfermedades);

        PanelAlergias.setLayout(new java.awt.BorderLayout());

        jPanel11.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Selecciona una alergia");

        ComboBoxAlergias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboBoxAlergias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecciona una opción>" }));
        ComboBoxAlergias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxAlergiasActionPerformed(evt);
            }
        });

        BotonAgregarAlergia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonAgregarAlergia.setText("Agregar al antecedente");
        BotonAgregarAlergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarAlergiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(ComboBoxAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(BotonAgregarAlergia, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(613, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAgregarAlergia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        PanelAlergias.add(jPanel11, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout PanelAntecedenteAlergiasLayout = new javax.swing.GroupLayout(PanelAntecedenteAlergias);
        PanelAntecedenteAlergias.setLayout(PanelAntecedenteAlergiasLayout);
        PanelAntecedenteAlergiasLayout.setHorizontalGroup(
            PanelAntecedenteAlergiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1265, Short.MAX_VALUE)
        );
        PanelAntecedenteAlergiasLayout.setVerticalGroup(
            PanelAntecedenteAlergiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        PanelAlergias.add(PanelAntecedenteAlergias, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Alergias", PanelAlergias);

        PanelVacunas.setLayout(new java.awt.BorderLayout());

        jPanel12.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Selecciona una vacuna");

        ComboBoxVacunas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboBoxVacunas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecciona una opción>" }));
        ComboBoxVacunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxVacunasActionPerformed(evt);
            }
        });

        BotonAgregarVacuna.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonAgregarVacuna.setText("Agregar al antecedente");
        BotonAgregarVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarVacunaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(ComboBoxVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(BotonAgregarVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(613, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAgregarVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        PanelVacunas.add(jPanel12, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout PanelAntecedenteVacunasLayout = new javax.swing.GroupLayout(PanelAntecedenteVacunas);
        PanelAntecedenteVacunas.setLayout(PanelAntecedenteVacunasLayout);
        PanelAntecedenteVacunasLayout.setHorizontalGroup(
            PanelAntecedenteVacunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1265, Short.MAX_VALUE)
        );
        PanelAntecedenteVacunasLayout.setVerticalGroup(
            PanelAntecedenteVacunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        PanelVacunas.add(PanelAntecedenteVacunas, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Vacunas", PanelVacunas);

        PanelCirugias.setLayout(new java.awt.BorderLayout());

        jPanel13.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Selecciona una cirugía");

        ComboBoxCirugias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboBoxCirugias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecciona una opción>" }));
        ComboBoxCirugias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCirugiasActionPerformed(evt);
            }
        });

        BotonAgregarCirugia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonAgregarCirugia.setText("Agregar al antecedente");
        BotonAgregarCirugia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarCirugiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(ComboBoxCirugias, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(BotonAgregarCirugia, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(613, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxCirugias, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAgregarCirugia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        PanelCirugias.add(jPanel13, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout PanelAntecedenteCirugiasLayout = new javax.swing.GroupLayout(PanelAntecedenteCirugias);
        PanelAntecedenteCirugias.setLayout(PanelAntecedenteCirugiasLayout);
        PanelAntecedenteCirugiasLayout.setHorizontalGroup(
            PanelAntecedenteCirugiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1265, Short.MAX_VALUE)
        );
        PanelAntecedenteCirugiasLayout.setVerticalGroup(
            PanelAntecedenteCirugiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        PanelCirugias.add(PanelAntecedenteCirugias, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Cirugías", PanelCirugias);

        PanelMedicamentos.setLayout(new java.awt.BorderLayout());

        jPanel14.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Selecciona un medicamento");

        ComboBoxMedicamentos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboBoxMedicamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecciona una opción>" }));
        ComboBoxMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMedicamentosActionPerformed(evt);
            }
        });

        BotonAgregarMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonAgregarMedicamento.setText("Agregar al antecedente");
        BotonAgregarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarMedicamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(ComboBoxMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(BotonAgregarMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(613, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAgregarMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        PanelMedicamentos.add(jPanel14, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout PanelAntecedenteMedicamentosLayout = new javax.swing.GroupLayout(PanelAntecedenteMedicamentos);
        PanelAntecedenteMedicamentos.setLayout(PanelAntecedenteMedicamentosLayout);
        PanelAntecedenteMedicamentosLayout.setHorizontalGroup(
            PanelAntecedenteMedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1265, Short.MAX_VALUE)
        );
        PanelAntecedenteMedicamentosLayout.setVerticalGroup(
            PanelAntecedenteMedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        PanelMedicamentos.add(PanelAntecedenteMedicamentos, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Medicamentos", PanelMedicamentos);

        jTabbedPane1.setSelectedComponent(PanelEnfermedades);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ANTECECEDENTES MÉDICOS");
        jLabel3.setAlignmentX(0.5F);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel8.add(jLabel3, java.awt.BorderLayout.CENTER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Recursos/icono_regresar.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        jPanel8.add(jLabel2, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(955, 955, 955))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Enfermedades");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxEnfermedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxEnfermedadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxEnfermedadesActionPerformed

    private void BotonAgregarEnfermedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarEnfermedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAgregarEnfermedadActionPerformed

    private void ComboBoxAlergiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxAlergiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxAlergiasActionPerformed

    private void BotonAgregarAlergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarAlergiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAgregarAlergiaActionPerformed

    private void ComboBoxVacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxVacunasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxVacunasActionPerformed

    private void BotonAgregarVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarVacunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAgregarVacunaActionPerformed

    private void ComboBoxCirugiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCirugiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxCirugiasActionPerformed

    private void BotonAgregarCirugiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarCirugiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAgregarCirugiaActionPerformed

    private void ComboBoxMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxMedicamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxMedicamentosActionPerformed

    private void BotonAgregarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAgregarMedicamentoActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroAntecedente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroAntecedente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroAntecedente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroAntecedente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroAntecedente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarAlergia;
    private javax.swing.JButton BotonAgregarCirugia;
    private javax.swing.JButton BotonAgregarEnfermedad;
    private javax.swing.JButton BotonAgregarMedicamento;
    private javax.swing.JButton BotonAgregarVacuna;
    private javax.swing.JComboBox<String> ComboBoxAlergias;
    private javax.swing.JComboBox<String> ComboBoxCirugias;
    private javax.swing.JComboBox<String> ComboBoxEnfermedades;
    private javax.swing.JComboBox<String> ComboBoxMedicamentos;
    private javax.swing.JComboBox<String> ComboBoxVacunas;
    private javax.swing.JPanel PanelAlergias;
    private javax.swing.JPanel PanelAntecedenteAlergias;
    private javax.swing.JPanel PanelAntecedenteCirugias;
    private javax.swing.JPanel PanelAntecedenteEnfermedades;
    private javax.swing.JPanel PanelAntecedenteMedicamentos;
    private javax.swing.JPanel PanelAntecedenteVacunas;
    private javax.swing.JPanel PanelCirugias;
    private javax.swing.JPanel PanelEnfermedades;
    private javax.swing.JPanel PanelMedicamentos;
    private javax.swing.JPanel PanelVacunas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
